\set ON_ERROR_STOP on
-- Orders CDC onboarding: runs once, as the postgres superuser, as part of
-- bringing the orders table onto the change-capture pipeline.

-- 1. Drop any existing replication slot before the schema changes underneath
-- it, so the connector's next start performs one clean initial snapshot.
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_replication_slots WHERE slot_name = 'debezium') THEN
    PERFORM pg_terminate_backend(active_pid) FROM pg_replication_slots
      WHERE slot_name = 'debezium' AND active_pid IS NOT NULL;
    PERFORM pg_drop_replication_slot('debezium');
  END IF;
END $$;

-- 2. Replace the orders table with one partitioned by RANGE (created_at).
-- order_items.order_id becomes an informational reference rather than an
-- enforced foreign key, since a partitioned table's primary key must
-- include the partition key.
DROP TABLE public.orders CASCADE;

CREATE TABLE public.orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  customer_id INTEGER NOT NULL REFERENCES public.customers(id),
  status TEXT NOT NULL DEFAULT 'pending',
  total NUMERIC(10, 2) NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (id, created_at)
) PARTITION BY RANGE (created_at);

CREATE INDEX idx_orders_customer_id ON public.orders (customer_id);
CREATE INDEX idx_orders_status ON public.orders (status);
ALTER TABLE public.orders REPLICA IDENTITY FULL;

-- 3. Partition-name registry: the one place the previous and current
-- month's partition names and bounds are recorded, so every later reader
-- (the repair Job, the observer/verifier) looks them up here instead of
-- each independently re-deriving 'orders_' || to_char(date_trunc('month',
-- ...), 'YYYY_MM') from its own call to now(). Operational metadata, not
-- part of the fix: kept out of cdc_publication and out of Debezium's
-- table.include.list (application.properties.tftpl's regex only matches
-- orders_YYYY_MM), so it is solver-readable via psql without naming the fix
-- itself.
CREATE TABLE public.cdc_partition_registry (
  role           text PRIMARY KEY,
  partition_name text NOT NULL,
  range_start    date,
  range_end      date,
  created_at     timestamptz DEFAULT now()
);

-- 4. Previous and current month partitions, named and bounded relative to
-- the real clock, and recorded into cdc_partition_registry from the same
-- derivation that creates them -- one computation, not one per reader.
-- REPLICA IDENTITY FULL is set explicitly on each partition, since it does
-- not cascade from a partitioned parent before PostgreSQL 17.
DO $$
DECLARE
  prev_start date := date_trunc('month', now() - interval '1 month');
  prev_end   date := date_trunc('month', now());
  curr_start date := date_trunc('month', now());
  curr_end   date := date_trunc('month', now() + interval '1 month');
  prev_name  text := 'orders_' || to_char(prev_start, 'YYYY_MM');
  curr_name  text := 'orders_' || to_char(curr_start, 'YYYY_MM');
BEGIN
  EXECUTE format('CREATE TABLE public.%I PARTITION OF public.orders FOR VALUES FROM (%L) TO (%L)',
    prev_name, prev_start, prev_end);
  EXECUTE format('ALTER TABLE public.%I REPLICA IDENTITY FULL', prev_name);
  EXECUTE format('CREATE TABLE public.%I PARTITION OF public.orders FOR VALUES FROM (%L) TO (%L)',
    curr_name, curr_start, curr_end);
  EXECUTE format('ALTER TABLE public.%I REPLICA IDENTITY FULL', curr_name);

  INSERT INTO public.cdc_partition_registry (role, partition_name, range_start, range_end)
    VALUES ('previous', prev_name, prev_start, prev_end);
  INSERT INTO public.cdc_partition_registry (role, partition_name, range_start, range_end)
    VALUES ('current', curr_name, curr_start, curr_end);
END $$;

-- 5. Re-grant what the earlier bootstrap SQL granted on the table this
-- replaced.
GRANT ALL PRIVILEGES ON public.orders TO app;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO app;

-- 6. Table used to request an incremental snapshot on demand. Granted here,
-- not left to the scene's own default-privilege grant, since that grant only
-- covers tables created by the role that ran it, and this table is created
-- afterward by onboarding.sql running as the postgres superuser. The signal
-- channel is source/table-based (application.properties.tftpl: signal.
-- enabled.channels=source); the repair Job writes signal rows as the
-- postgres superuser, but the connector also writes its own open/close
-- window watermark rows into this table during an incremental snapshot
-- (emitWindowOpen), as the debezium role, so it needs INSERT as well as
-- SELECT.
CREATE TABLE public.debezium_signal (
  id VARCHAR(64) PRIMARY KEY,
  type VARCHAR(32) NOT NULL,
  data VARCHAR(2048)
);
GRANT SELECT, INSERT ON public.debezium_signal TO debezium;

-- 7. Publication for the change-capture pipeline: customers, products and
-- order_items carried over from the earlier bootstrap, plus the previous
-- month's orders partition (looked up in cdc_partition_registry, the same
-- name step 4 just created, not re-derived here) and the signal table.
DO $$
DECLARE
  prev_name text := (SELECT partition_name FROM public.cdc_partition_registry WHERE role = 'previous');
BEGIN
  EXECUTE format('ALTER PUBLICATION cdc_publication ADD TABLE public.%I', prev_name);
  EXECUTE 'ALTER PUBLICATION cdc_publication ADD TABLE public.debezium_signal';
END $$;

-- 8. A least-privilege role for acceptance probing: it can write a new
-- order, it can read order ids and timestamps on orders, and it can read
-- the partition registry (names and date bounds only, not the fix).
-- Nothing else.
CREATE ROLE cdc_probe LOGIN PASSWORD :'probe_password';
GRANT CONNECT ON DATABASE shop TO cdc_probe;
GRANT USAGE ON SCHEMA public TO cdc_probe;
GRANT INSERT ON public.customers, public.orders TO cdc_probe;
GRANT SELECT (id, created_at) ON public.orders TO cdc_probe;
GRANT SELECT ON public.cdc_partition_registry TO cdc_probe;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO cdc_probe;

-- 9. Seed data: previous-month orders (delivered) and current-month orders.
DO $$
DECLARE
  prev_start date := date_trunc('month', now() - interval '1 month');
  cust_id integer;
  i integer;
  backdated timestamptz;
BEGIN
  FOR i IN 1..60 LOOP
    INSERT INTO public.customers (name, email, tier)
      VALUES ('Seed Customer ' || i, 'seed-customer-' || i || '@cdc.invalid',
              CASE WHEN i % 5 = 0 THEN 'gold' ELSE 'standard' END)
      RETURNING id INTO cust_id;
    FOR j IN 1..(4 + (i % 2)) LOOP
      backdated := prev_start + make_interval(days => (i * 7 + j * 3) % 27,
                                                hours => (i + j) % 24);
      INSERT INTO public.orders (customer_id, status, total, created_at, updated_at)
        VALUES (cust_id, 'delivered', (20 + (i * j % 80))::numeric(10,2), backdated, backdated);
    END LOOP;
  END LOOP;

  FOR i IN 1..40 LOOP
    SELECT id INTO cust_id FROM public.customers ORDER BY random() LIMIT 1;
    INSERT INTO public.orders (customer_id, status, total)
      VALUES (cust_id, 'pending', (15 + (i * 3 % 60))::numeric(10,2));
  END LOOP;
END $$;

SELECT 'Applied orders release 0031 onboarding: partitioned schema, signal table, publication membership, seed data.' AS result;
