apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-credentials
  namespace: {{ .Values.namespace | quote }}
spec:
  refreshInterval: 10s
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-store
  target:
    name: db-credentials
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: "db-credentials-{{ .Values.namespace }}"
        version: "1"
